[workspace]
authors = ["Allen Guo <guosonglin001@gmail.com>"]
channels = ["conda-forge"]
name = "vllm-env"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "13.0"

[dependencies]
python = "3.13.*"
uv = ">=0.8.13,<0.9"

[target.linux-64.dependencies]
# triton = ">=3.4.0,<4"
# cusparselt = ">=0.8.0.4,<0.9"
# # pixi add cuda-version=12.9 cuda-toolkit=12.9.1 -p linux-64
# cuda-version = "12.9.*"
# cuda-toolkit = "12.9.1.*"
# # pixi add pytorch-gpu=2.8.0 -p linux-64
# pytorch-gpu = "2.8.0.*"

# pixi add cuda-version=13.0 cuda-toolkit=13.0.0 -p linux-64
# cuda-version = "13.0.*"
# cuda-toolkit = "13.0.0.*"
# pixi add cusparselt pytorch-gpu=2.10.0 -p linux-64
