[workspace]
authors = ["Allen Guo <guosonglin001@gmail.com>"]
channels = ["conda-forge"]
name = "vllm-env"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.12.13,<3.13"
uv = ">=0.8.24,<0.9"

zellij = ">=0.43.1,<0.44"
aria2 = ">=1.37.0,<2"
unzip = ">=6.0,<7"

huggingface_hub = ">=1.18.0,<2"
modelscope = ">=1.37.1,<2"

# cu129
[feature.cu129.system-requirements]
cuda = "12.9"

[feature.cu129.dependencies]
python = ">=3.12.13,<3.13"
uv = ">=0.8.24,<0.12"

[feature.cu129.target.linux-64.dependencies]
# CONDA_OVERRIDE_CUDA=12.9 pixi i -e cu129
# CONDA_OVERRIDE_CUDA=12.9 pixi add cuda-version=12.9 cuda-toolkit=12.9.2 -p linux-64 -f cu129
cuda-version = "12.9.*"
cuda-toolkit = "12.9.2.*"
# pixi add nomkl -p linux-64 -f cu129
nomkl = ">=1.0,<2"
# CONDA_OVERRIDE_CUDA=12.9 pixi add "pytorch[version='==2.11.0', build='*cuda129_generic*']" -p linux-64 -f cu129
pytorch = { version = "==2.11.0", build = "*cuda129_generic*" }
[feature.cu129.target.linux-64.pypi-dependencies]
# TODO: use conda version
# CONDA_OVERRIDE_CUDA=12.9 pixi add torchvision --pypi -p linux-64 -f cu129 --index https://download.pytorch.org/whl/cu129
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu129" }

# cu130
[feature.cu130.system-requirements]
cuda = "13.0"

[feature.cu130.dependencies]
python = ">=3.12.13,<3.13"
uv = ">=0.11.19,<0.12"

[feature.cu130.target.linux-64.dependencies]
# CONDA_OVERRIDE_CUDA=13.0 pixi i -e cu130
# CONDA_OVERRIDE_CUDA=13.0 pixi add cuda-version=13.0 cuda-toolkit=13.0 -p linux-64 -f cu130
cuda-version = "13.0.*"
cuda-toolkit = "13.0.*"
# pixi add nomkl -p linux-64 -f cu130
nomkl = ">=1.0,<2"
# CONDA_OVERRIDE_CUDA=13.0 pixi add "pytorch[version='==2.11.0', build='*cuda130_generic*']" -p linux-64 -f cu130
pytorch = { version = "==2.11.0", build = "*cuda130_generic*" }
[feature.cu130.target.linux-64.pypi-dependencies]
# CONDA_OVERRIDE_CUDA=13.0 pixi add torchvision --pypi -p linux-64 -f cu130 --index https://download.pytorch.org/whl/cu130
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu130" }

[environments]
# default is implicit
# default = { features = ["cu129"] }
# default = { features = ["cu130"] }
cu129 = { features = ["cu129"], no-default-feature = true }
cu130 = { features = ["cu130"], no-default-feature = true }

[activation.env]
HOME = "${PIXI_PROJECT_ROOT}/dot.home"
XDG_CONFIG_HOME = "${PIXI_PROJECT_ROOT}/dot.home/.config"
XDG_DATA_HOME = "${PIXI_PROJECT_ROOT}/dot.home/.data"
XDG_CACHE_HOME = "${PIXI_PROJECT_ROOT}/dot.home/.cache"
