[workspace]
authors = ["Allen Guo <guosonglin001@gmail.com>"]
channels = ["conda-forge"]
name = "vllm-env"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "13.0"

[dependencies]
python = "3.13.*"
uv = ">=0.8.13,<0.9"

[target.linux-64.dependencies]
# # uv pip install "pytorch-triton==3.4.0" -i https://download.pytorch.org/whl/cu129/
# # uv pip install "pytorch-triton-rocm==3.4.0" -i https://download.pytorch.org/whl/cu129/
# # uv pip install "pytorch-triton-xpu==3.4.0" -i https://download.pytorch.org/whl/cu129/
# triton = ">=3.4.0,<4"
# cusparselt = ">=0.8.0.4,<0.9"
# # pixi add cuda-version=12.9 cuda-toolkit=12.9.1 -p linux-64
# cuda-version = "12.9.*"
# cuda-toolkit = "12.9.1.*"
# # pixi add pytorch-gpu=2.8.0 -p linux-64
# pytorch-gpu = "2.8.0.*"
